#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

site_name: Apache Celeborn™ (Incubating)
repo_name: apache/incubator-celeborn
repo_url: https://gitbox.apache.org/repos/asf/incubator-celeborn.git

plugins:
  - search
  - macros
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"

theme:
  font: false
  name: material
  language: en
  logo: assets/logo/celeborn-1.svg
  favicon: assets/logo/celeborn-2.svg
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github

copyright: >
  <img src="https://www.apachecon.com/event-images/acna2022-wide-dark.png" style="height: 100px;" alt="ApacheCon North America">
  <img src="https://incubator.apache.org/images/incubator_feather_egg_logo_bw_crop.png" style="height: 87px; margin: 0 0 10px 0;">
  <br>
  Copyright © 2022 The Apache Software Foundation
  <a href="https://privacy.apache.org/policies/privacy-policy-public.html">Privacy Policy<a/><br>
  <br>
  Apache Celeborn™, Apache Incubator, Apache, the Apache feather logo, and the Apache Incubator project logo are
  trademarks or registered trademarks of The Apache Software Foundation.<br>
  <br>
  Apache Celeborn™ is an effort undergoing incubation at The Apache Software Foundation (ASF), sponsored by the
  Apache Incubator. Incubation is required of all newly accepted projects until a further review indicates that
  the infrastructure, communications, and decision making process have stabilized in a manner consistent with
  other successful ASF projects. While incubation status is not necessarily a reflection of the completeness or
  stability of the code, it does indicate that the project has yet to be fully endorsed by the ASF.<br>
  <br>
  Please visit <a href="https://www.apache.org/">Apache Software Foundation</a> for more details.<br>
  <br>

nav:
  - Configuration: configuration/index.md
  - Deployment:
      - Overview: deploy.md
      - Kubernetes: deploy_on_k8s.md
      - Upgrade: upgrade.md
      - Ratis Shell: celeborn_ratis_shell.md
      - Cluster Planning: cluster_planning.md
  - Monitoring: monitoring.md
  - Migration Guide: migration.md

